apiVersion: v1
kind: Service
metadata:
  name: user-ui-svc
  namespace: {{ include "ui.namespace" . }} #namespace
  labels:
   {{- include "ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: user-ui
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}