#configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-cm-name" . }}
  namespace: {{ include "api-namespace" . }}
  labels:
   {{- include "api-labels" . | nindent 4 }}
data:
  email: {{ .Values.configMap.email }}