apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-secret-name" . }}
  namespace: {{ include "api-namespace" . }}
  labels:
   {{- include "api-labels" . | nindent 4 }}
type: Opaque
data:
  connectionstring: {{ .Values.secret.connectionstring }}
