#configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-ui-cm
  namespace: admin
  labels:
    module: admin
    env: dev
data:
  .env: |
      REACT_APP_API_URL= http://localhost:1026 
      
---
#service.yml
apiVersion: v1
kind: Service
metadata:
  name: admin-ui-svc
  namespace: admin
  labels:
    module: admin
    env: dev
spec:
  type: NodePort
  selector:
    app: admin-ui
  ports:
  - port: 3001
    targetPort: 3000

---
#deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
  namespace: admin
  labels:
    module: admin
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: admin-ui
  template:
    metadata:
      labels:
        app: admin-ui
        module: admin
        env: dev
    spec:
      containers:
      - name: admin-ui
        image: harshsoni777/admin-ui:v1
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name:  admin-ui-vi
          mountPath:  /app/.env
          subPath: .env
        # livenessProbe:
        #   httpGet:
        #     path: /health 
        #     port: 3000
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
      volumes:
      - name:  admin-ui-vi
        configMap:
          name: admin-ui-cm
