apiVersion: v1
kind: Service
metadata:
  name: admin-ui-svc
  namespace: admin
  labels:
    module: admin
    env: dev
spec:
  type: NodePort
  selector:
    app: admin-ui
  ports:
  - port: 3001
    targetPort: 3000
