apiVersion: v1
kind: Service
metadata:
  name: admin-api-svc
  namespace: {{ include "api-namespace" . }}
  labels:
   {{- include "api-labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: admin-api
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}