#configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-ui-cm
  namespace: user
  labels:
    module: user
    env: dev
data:
  .env: |
      REACT_APP_API_URL= http://localhost:1025
---
#service.yml
apiVersion: v1
kind: Service
metadata:
  name: user-ui-svc
  namespace: user
  labels:
    module: user
    env: dev
spec:
  type: NodePort
  selector:
    app: user-ui
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32005

---
#deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui
  namespace: user
  labels:
    module: user
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-ui
  template:
    metadata:
      labels:
        app: user-ui
        module: user
        env: dev
    spec:
      containers:
      - name: user-ui
        image: harshsoni777/user-ui:v1
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        ports:
        - containerPort: 3000
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 5
        #   failureThreshold: 5
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        volumeMounts:
        - name:  user-ui-vi
          mountPath:  /app/.env
          subPath: .env
      volumes:
      - name:  user-ui-vi
        configMap:
          name: user-ui-cm
    