apiVersion: v1
kind: Service
metadata:
  name: user-ui-svc
  namespace: user
  labels:
    module: user
    env: dev
spec:
  type: NodePort
  selector:
    app: user-ui
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32005
