apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-pvc
  namespace: database
  labels:
    module: database
    env: dev
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
