apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-db-pv
  namespace: database
  labels:
    app: mongo-db-pv
    module: database
    env: dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data