#Secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name:  admin-api-secrets
  namespace: admin
  labels:
    module: admin
    env: dev
data:
   connectionstring: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvLWRiLXN2Yy5kYXRhYmFzZS5zdmMuY2x1c3Rlci5sb2NhbC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5Cg==
type: Opaque

#mongodb://mongoadmin:secret@mongo-db-svc.database.svc.cluster.local/?retryWrites=true&w=majority

---
#Service.yml
apiVersion: v1
kind: Service
metadata:
  name: admin-api-svc
  namespace: admin
  labels:
    module: admin
    env: dev
spec:
  type: NodePort
  selector:
    app: admin-api
  ports:
  - port: 1026
    targetPort: 1026
    nodePort: 32003

#Deployment.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
  namespace: admin
  labels:
    module: admin
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
        module: admin
        env: dev
    spec:
      containers:
      - name: admin-api
        image: harshsoni777/admin-api:v1
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        ports:
        - containerPort: 1026
          name: http
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name:  admin-api-secrets
                key:  connectionstring
          - name: PORT
            value: "1026"
        livenessProbe:
          httpGet:
            path: /api/health 
            port: 1026
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 1026
          initialDelaySeconds: 30
          timeoutSeconds: 10