apiVersion: v1
kind: Service
metadata:
  name: admin-api-svc
  namespace: admin
  labels:
    module: admin
    env: dev
spec:
  type: NodePort
  selector:
    app: admin-api
  ports:
  - port: 1026
    targetPort: 1026
    nodePort: 32003