apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ui-cm-name" . }}
  namespace: {{ include "ui-namespace" . }}
  labels:
   {{- include "ui-labels" . | nindent 4 }}
data:
  .env: |
      {{ .Values.configmap.env }}
      