apiVersion: v1
kind: Service
metadata:
  name: admin-ui-svc
  namespace: {{ include "admin.ui.namespace" . }}
  labels:
   {{- include "admin.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: admin-ui
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}