apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin.ui.cm.name" . }}
  namespace: {{ include "admin.ui.namespace" . }}
  labels:
   {{- include "admin.ui.labels" . | nindent 4 }}
data:
  .env: |
      {{ .Values.configmap.env }}
      