apps:
  replicas: 1
  env: dev
  image: harshsoni777/admin-ui:9
  name: admin-ui
  computers:
    requests:
      cpu: "250m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"
  
  containerPort: 3000

volume:
  name:  admin-ui-vi

service:
  port: 3001
  targetPort: 3000
  type: NodePort

configmap:
  env: REACT_APP_API_URL= http://localhost:1026