apiVersion: v2
name: my-app
description: A Helm chart to deploy multiple microservices
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:

  - name: db
    version: 0.1.0
    repository: file://charts/db

  - name: admin-api
    version: 0.1.0
    repository: file://charts/admin-api

  - name: user-api
    alias: user-api
    version: 0.1.0
    repository: file://charts/user-api

  - name: admin-ui
    version: 0.1.0
    repository: file://charts/admin-ui

  - name: user-ui
    version: 0.1.0
    repository: file://charts/user-ui
