global:
  env: prod  # Change to "qa" or "prod" when deploying different environments

db:
  db:
    replicas: 5
    env: prod
    name: mongo-db

    containerPort: 27017

    computers:
      requests:
        cpu: "2000m"
        memory: "3Gi"
      limits:
        cpu: "2500m"
        memory: "12Gi"

  secret:
    dbuser: bW9uZ29hZG1pbg==
    dbpass: c2VjcmV0

admin_api:
  apps:
    replicas: 4
    env: prod
    name: admin-api
    image: harshsoni777/admin-api:v20
    computers:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1000m"
        memory: "8Gi"
    containerPort: 1026

  service:
    port: 1026
    targetPort: 1026
    nodePort: 32003
    type: NodePort
  secrets:
    connectionString: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvLWRiLXN2Yy5kYXRhYmFzZS5zdmMuY2x1c3Rlci5sb2NhbC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5Cg==

user_api:
  apps:
    replicas: 4
    env: prod
    image: harshsoni777/user-api:v20
    name: user-api
    computers:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1000m"
        memory: "8Gi"

    containerPort: 1025
    containerName: user-api
    portName: http
  

  service:
    port: 1024
    targetPort: 1025
    nodePort: 32004
    type: NodePort
  secret:
    connectionstring: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvLWRiLXN2Yy5kYXRhYmFzZS5zdmMuY2x1c3Rlci5sb2NhbC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5Cg==
  configMap:
    email: harshsoni6011@gmail.com


admin_ui:
  apps:
    replicas: 4
    env: dev
    image: harshsoni777/admin-ui:v20
    name: admin-ui
    computers:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1000m"
        memory: "8Gi"

    containerPort: 3000

  volume:
    name:  admin-ui-vi
  service:
    port: 3001
    targetPort: 3000
    type: NodePort


configmap:
  env: REACT_APP_API_URL= http://localhost:1026

user_ui:
  apps:
    replicas: 4
    env: prod
    name: user-ui
    computers:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1000m"
        memory: "8Gi"
    image: harshsoni777/user-ui:v20
    containerPort: 3000

  hpa:
    enabled: true
    minReplicas: 4
    maxReplicas: 8
    averageUtilization: 50

  service:
    port: 3000
    targetPort: 3000
    nodePort: 32005
    type: NodePort

  volume:
    name: user-ui-vi #volume and volumeMount Name
    
  configMap:
    env: REACT_APP_API_URL= http://localhost:1025   