#secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.secret.name" . }}  # Ensure space before include
  namespace: {{ include "db.namespace" . }}  # Correct namespace key
  
  labels:
    {{- include "db.labels" . | nindent 4 }}
type: Opaque
data:
  dbuser: {{ .Values.secret.dbuser }}
  dbpass: {{ .Values.secret.dbpass }}