apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.svc.name" . }}  # Ensure space before include
  namespace: {{ include "db.namespace" . }}  # Correct namespace key
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  selector:
    app: mongo-db
  ports:
  - port: 27017
    targetPort: dbport