apps:
  replicas: 4
  env: prod
  name: user-ui
  computers:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "8Gi"
  image: harshsoni777/user-ui:v98
  containerPort: 3000

hpa:
  enabled: true
  minReplicas: 4
  maxReplicas: 8
  averageUtilization: 50

service:
  port: 3000
  targetPort: 3000
  nodePort: 32005
  type: NodePort

volume:
  name: user-ui-vi #volume and volumeMount Name

configMap:
  env: REACT_APP_API_URL= http://localhost:1025