db:
  replicas: 5
  env: prod
  name: mongo-db

  containerPort: 27017

  computers:
    requests:
      cpu: "2000m"
      memory: "3Gi"
    limits:
      cpu: "2500m"
      memory: "12Gi"

secret:
  dbuser: bW9uZ29hZG1pbg==
  dbpass: c2VjcmV0