db:
  replicas: 1
  env: dev
  name: mongo-db

  containerPort: 27017

  computers:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1500m"
      memory: "8Gi"

secret:
  dbuser: bW9uZ29hZG1pbg==
  dbpass: c2VjcmV0