db:
  replicas: 3
  env: qa
  name: mongo-db

  containerPort: 27017

  computers:
    requests:
      cpu: "1500m"
      memory: "2.5Gi"
    limits:
      cpu: "2000m"
      memory: "10Gi"

secret:
  dbuser: bW9uZ29hZG1pbg==
  dbpass: c2VjcmV0