apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.name }}-{{ .Release.Name }}
  namespace: {{ include "admin.api.namespace" . }}
  labels:
   {{- include "admin.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apps.replicas }}
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
       {{- include "admin.api.labels" . | nindent 8 }}
    spec:
      containers:
      - name: admin-api
        image: {{ .Values.apps.image }}
        resources:
          {{- toYaml .Values.apps.computers | nindent 10 }}
        ports:
        - containerPort: {{ .Values.apps.containerPort }}
          name: http
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "admin.api.secret.name" . }}
                key:  connectionstring
          - name: PORT
            value: "1026"
        livenessProbe:
          httpGet:
            path: /api/health 
            port: 1026
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 1026
          initialDelaySeconds: 30
          timeoutSeconds: 10
