apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admin.api.secret.name" . }}
  namespace: {{ include "admin.api.namespace" . }}
  labels:
    {{- include "admin.api.labels" . | nindent 4 }}
data:
   connectionstring: {{ .Values.secrets.connectionString }}
type: Opaque