apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user.api.secret.name" . }}
  #user-api
  namespace: {{ include "user.api.namespace" . }}
  labels:
   {{- include "user.api.labels" . | nindent 4 }}
type: Opaque
data:
  connectionstring: {{ .Values.secret.connectionstring }}
