#configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-api-cm
  namespace: user
  labels:
    module: user
    env: dev
data:
  email: harshsoni6011@gmail.com

---
#secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: user-api-secrets
  namespace: user
  labels:
    module: user
    env: dev
type: Opaque
data:
  connectionstring: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvLWRiLXN2Yy5kYXRhYmFzZS5zdmMuY2x1c3Rlci5sb2NhbC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5Cg==

---
#service.yml
apiVersion: v1
kind: Service
metadata:
  name: user-api-svc
  namespace: user
  labels:
    module: user
    env: dev
spec:
  type: NodePort
  selector:
    app: user-api
  ports:
  - port: 1025
    targetPort: 1025
    nodePort: 32004


---
#deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  namespace: user
  labels:
    module: user
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
        module: user
        env: dev
    spec:
      containers:
      - name: user-api
        image: harshsoni777/user-api:v1
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        ports:
        - containerPort: 1025
          name: http
        env:
        - name:  MONGO_URL
          valueFrom:
            secretKeyRef:
              name: user-api-secrets
              key: connectionstring
        - name: PORT
          value: "1025"
        - name: ADMIN_EMAIL
          valueFrom:
            configMapKeyRef:
              name: user-api-cm
              key: email
        livenessProbe:
          httpGet:
            path: /api/health
            port: 1025
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 1025
          initialDelaySeconds: 30
          timeoutSeconds: 10
