apiVersion: v1
kind: Service
metadata:
  name: user-api-svc
  namespace: user
  labels:
    module: user
    env: dev
spec:
  type: NodePort
  selector:
    app: user-api
  ports:
  - port: 1025
    targetPort: 1025
    nodePort: 32004
