apps:
  replicas: 4
  env: prod
  image: harshsoni777/user-api:v1
  name: user-api
  computers:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "8Gi"
  
  containerPort: 1025
  containerName: user-api
  portName: http
  

service:
  port: 1024
  targetPort: 1025
  nodePort: 32004
  type: NodePort

secret:
  connectionstring: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvLWRiLXN2Yy5kYXRhYmFzZS5zdmMuY2x1c3Rlci5sb2NhbC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5Cg==

configMap:
  email: harshsoni6011@gmail.com
